title: 绫中之书 #博客标题
description: 冬日凛冽屋中暖，银松傲立风雪中。 #博客描述
keywords: blog,css,html,js,javascripts,androidstuido,c# #博客关键字
author: "JDSALing"

#title hide and show
hide: 书中自有黄金屋
show: 愿与阅者寻归途

# markdown: kramdown
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 1
#     coderay_bold_every: 0
#     coderay_css: style

#   /*th,
#  td {
#    padding: 0.5rem 1rem;
#    border: 1px solid $table-border-color;
#  }
#  */


pygments: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "jdsalingzx.top" # change this to the base hostname & protocol for your site
buildtime: "1652774400" 
#博客建立时的时间戳 可进入https://tool.lu/timestamp/
#将博客建立时的日期转换成时间戳
#The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: false #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 3 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://rust.coldmint.top/ftp/ling/cdnpng/snow.jpg
theme_color: 00adf294

# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: true

#install emoji
plugins:
  - jemoji

# social account
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
