title: 绫中之书 #博客标题
description: 书中自有黄金屋，愿与阅者寻归途。 #博客描述
keywords: blog,css,html,js,javascripts,androidstuido #博客关键字
author: "JDSALing"

#title hide and show
hide: (つェ⊂)待会见
show: ´∇｀ 欢迎回来~

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "jdsalingzx.top" # change this to the base hostname & protocol for your site
buildtime: "1652716800" 
#博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
#The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://jdsalingzx.top/assets/img/header/search-magicgirl.jpeg
theme_color: 1BB6BE

# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji

# social account
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
